[character]
format = "$symbol "
success_symbol = "[➜](purple)"
error_symbol = "[➜](red)"

[directory]
style = "blue"

[cmd_duration]
format = "[$duration](yellow)"

[git_branch]
symbol = ""
style = "#808080"

[git_status]
format = "[$ahead_behind$all_status ](red)"
ahead = "⇡${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
behind = "⇣${count} "

[git_metrics]
disabled = false
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[gcloud]
disabled = true
