---
- name: create wofi config dir
  file:
    path: ~/.config/wofi
    state: directory

- name: template wofi style
  template:
    src: style.j2
    dest: ~/.config/wofi/style.css

- name: copy wofi config
  copy:
    src: config
    dest: ~/.config/wofi/

- name: copy wofi powermenu
  template:
    src: powermenu.sh.j2
    dest: ~/.config/wofi/powermenu.sh
    mode: 0755
