---

- name: create sway config dir
  file:
    path: ~/.config/sway/
    state: directory

- name: copy configuration file
  template:
    src: config.j2
    dest: ~/.config/sway/config

- name: autostart sway
  template:
    src: sway.fish.j2
    dest: ~/.config/fish/conf.d/sway.fish

- name: copy gsettings importer
  copy:
    src: import-gsettings
    dest: ~/.config/sway/
    mode: 0755

- name: copy config user.dirs
  copy:
    src: user-dirs.dirs
    dest: ~/.config/

- name: create kanshi config dir
  file:
    path: ~/.config/kanshi
    state: directory

- name: copy kanshi config file
  copy:
    src: "kanshi/by_host/{{ ansible_hostname }}/config"
    dest: ~/.config/kanshi/
  failed_when: false

- name: fish swaylock-fancy
  copy:
    src: swaylock.fish
    dest: ~/.config/fish/functions

- name: create xdg-desktop-wlr config dir
  file:
    path: ~/.config/xdg-desktop-portal-wlr/
    state: directory

- name: configure xdg-desktop-wlr to select display
  copy:
    src: config
    dest: ~/.config/xdg-desktop-portal-wlr/config

- name: configure zoom for wayland sharing
  copy:
    src: zoomus.conf
    dest: /home/user/.var/app/us.zoom.Zoom/config/zoomus.conf

