---

- name: create sway config dir
  file:
    path: ~/.config/sway/
    state: directory

- name: copy configuration file
  template:
    src: config.j2
    dest: ~/.config/sway/config

- name: autostart sway
  template:
    src: sway.fish.j2
    dest: ~/.config/fish/conf.d/sway.fish

- name: create swaylock dir config
  file:
    path: ~/.config/swaylock/
    state: directory

- name: copy swaylock config
  copy:
    src: swaylock.config
    dest: ~/.config/swaylock/config

- name: copy gsettings importer
  copy:
    src: import-gsettings
    dest: ~/.config/sway/
    mode: 0755

- name: copy config user.dirs
  copy:
    src: user-dirs.dirs
    dest: ~/.config/

- name: create kanshi config dir
  file:
    path: ~/.config/kanshi
    state: directory

- name: copy kanshi config file
  copy:
    src: "kanshi/by_host/{{ ansible_hostname }}/config"
    dest: ~/.config/kanshi/
  failed_when: false
