---
- name: create pipewire directory
  file:
    path: '{{ item }}'
    state: directory
  loop:
    - ~/.config/pipewire/
    - ~/.config/pipewire/pipewire.conf.d
  when: ansible_distribution == 'Void'

- name: configure pipewire
  copy:
    src: '{{ item }}'
    dest: ~/.config/pipewire/pipewire.conf.d/
  loop:
    - 10-wireplumber.conf
    - 20-pipewire-pulse.conf
  when: ansible_distribution == 'Void'
